name: Github Actions Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build and push:

    runs-on: ubuntu-latest
    name: A job to build and push docker

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Unit Tests
      run: mvn -B test --file pom.xml

    - name: Build with Maven
      run: |
        mvn clean
        mvn -B package --file pom.xml
        
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        dockerfile: Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo:today
        
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Push to docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        dockerfile: Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo:today
        
        
        
       
     

   
